config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clients
  resources :products
  resources :pedidos
  resources :order_histories
  root to: "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :pedidos
    has_many :order_histories
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
  belongs_to :client
  belongs_to :product
  belongs_to :pedido
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  validates :cantidad, presence: true, numericality: { only_integer: true }
  validates :precio, presence: true, numericality: { only_integer: true }
  validates :total, presence: true, numericality: { only_integer: true }
  belongs_to :cliente
  belongs_to :product

  has_many :pedidos
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :pedidos
    has_many :order_histories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
      def index
        @clients = Client.all
      end
    
     
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
        
    end
end

app/controllers/order_histories_controller.rb
class OrderHistoriesController < ApplicationController
    def index 
        
    end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
    def index 
        
    end
    def new 
        
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index 
        
    end
    def new 
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/order_histories_helper.rb
module OrderHistoriesHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/clients/index.html.erb
<h3 class="text-center mb-5">Lista de clientes</h3>
<button class="btn btn-secondary mb-3">Agregar cliente</button>
<table class="table">
  <thead>
    <tr>
      
      <th scope="col">Nombre</th>
      <th scope="col">Teléfono</th>
      <th scope="col">Colonia</th>
      <th scope="col">Calle</th>
      <th scope="col">N° de casa</th>
      <th scope="col">Referencia</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
    <tr>
      <td><%= client.nombre %></td>
      <td><%= client.telefono %></td>
      <td><%= client.colonia %></td>
      <td><%= client.calle %></td>
      <td><%= client.numero_casa %></td>
      <td><%= client.referencia %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/homes/index.html.erb
<div class="row row-cols-1 row-cols-md-2">
  <div class="col mb-4">
    <div class="card text-center">
      <%# <img src="..." class="card-img-top" alt="..."> %>
      <div class="card-body">
        <h5 class="card-title">Ver Productos</h5>
        <p class="card-text"><img src="https://img.icons8.com/fluent/80/000000/hamper.png"/></p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card text-center">
      <%# <img src="..." class="card-img-top" alt="..."> %>
      <div class="card-body">
        <h5 class="card-title">Nuevo Pedido</h5>
        <p class="card-text"><img src="https://img.icons8.com/color/80/000000/add-folder.png"/></p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card text-center">
      <%# <img src="..." class="card-img-top" alt="..."> %>
      <div class="card-body">
        <h5 class="card-title">Clientes</h5>
        <p class="card-text"><img src="https://img.icons8.com/officel/80/000000/user-group-man-man.png"/></p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card text-center">
      <%# <img src="..." class="card-img-top" alt="..."> %>
      <div class="card-body">
        <h5 class="card-title">Historial Ordenes</h5>
        <p class="card-text"><img src="https://img.icons8.com/cotton/80/000000/purchase-order.png"/></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DonBotasMeat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'shared/navbar' %>
      
    <% else %>
    <!-- Image and text -->
      <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">
          DonBotasMeat
        </a>
      </nav>
      <div class="container mt-5">
        <%= yield %>
      </div>
    <% end %>
    
  </body>
</html>

app/views/pedidos/new.html.erb
<h5>template de pedidos</h5>

app/views/products/new.html.erb
    <div class="card shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-body">
            <h1>dasdsa</h1>
             
        </div>
    </div>

app/views/shared/_deck.html.erb
<div class="container">
    <div class="card shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-body">
            <div class="card-deck">
                <div class="card">
                    <img src="..." class="card-img-top" alt="...">
                    <div class="card-body">
                        <%= link_to "Products", new_product_path %>
                    </div>
                </div>
                <div class="card">
                    <img src="..." class="card-img-top" alt="...">
                    <div class="card-body">
                    
                    </div>
                </div>
                <div class="card">
                    <img src="..." class="card-img-top" alt="...">
                    <div class="card-body">
                    
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-2">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-center" id="navbarText">
    <ul class="navbar-nav">
      <a class="navbar-brand" href="#">Don Botas</a>
    </ul>
  </div>
  <span class="navbar-text">
      <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
  </span>
   
</nav>

<ul class="nav nav-pills justify-content-center mb-2">
  <li class="nav-item"> 
    <% if current_page?(root_path) %>
      <%= link_to "Inicio", root_path, class:"nav-link active" %>
    <% else %>
      <%= link_to "Inicio", root_path, class:"nav-link" %>
    <% end %>
  </li>
  <li class="nav-item">
    <% if current_page?(products_path) %>
      <%= link_to "Productos", products_path, class:"nav-link active" %>
    <% else %>
      <%= link_to "Productos", products_path, class:"nav-link" %>
    <% end %>
  </li>
  <li class="nav-item">
    <% if current_page?(pedidos_path) %>
      <%= link_to "Pedidos", pedidos_path, class:"nav-link active" %>
    <% else %>
      <%= link_to "Pedidos", pedidos_path, class:"nav-link" %>
    <% end %>
  </li>
  <li class="nav-item">
    <% if current_page?(clients_path) %>
      <%= link_to "Clientes", clients_path, class:"nav-link active" %>
    <% else %>
      <%= link_to "Clientes", clients_path, class:"nav-link" %>
    <% end %>
  </li>
  <li class="nav-item">
    <% if current_page?(order_histories_path) %>
      <%= link_to "Ordenes", order_histories_path, class:"nav-link active" %>
    <% else %>
      <%= link_to "Ordenes", order_histories_path, class:"nav-link" %>
    <% end %>
  </li>
</ul>

<div class="container">
    <div class="card shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-body">
            <%= yield %>
            
        </div>
    </div>
</div>